version: "3.8"

services:
  api:
    build:
      context: './api/docker'
    depends_on:
      - db
    volumes:
      - './api/src:/var/www/api'
    privileged: true  
    ports:
      - '80:80'
    links:
      - db
  db:
    image: "mariadb"
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - '3306:3306'  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
