FROM mysql

# ADD ./config/01_cornet_tables.sql /docker-entrypoint-initdb.d
# ADD ./config/02_cornet_initial_data.sql /docker-entrypoint-initdb.d
# ADD ./config/11_project_tables.sql /docker-entrypoint-initdb.d
# ADD ./config/12_project_initial_data.sql /docker-entrypoint-initdb.d
# ADD ./config/13_project_initial_data.sql /docker-entrypoint-initdb.d
# ADD ./config/91_unittest_db.sh /docker-entrypoint-initdb.d
# ADD ./config/92_unittest_tables.sh /docker-entrypoint-initdb.d
